[package]
name = "company_house_monitoring"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.40"
diesel = { version = "2.2.8", features = ["postgres", "uuid", "chrono"] }
uuid = "1.16.0"
